"""PrioritySpec matching against the subject spellings the sources actually produce."""
from pathlib import Path

from scraper.sources.base import PrioritySpec

PRIORITY_FILE = Path(__file__).resolve().parents[1] / "config" / "priority_courses.txt"


def test_normalize_strips_spaces_inside_the_subject() -> None:
    assert PrioritySpec.normalize(" el  eng   16a ") == "ELENG 16A"
    assert PrioritySpec.normalize("POL SCI 1") == "POLSCI 1"
    assert PrioritySpec.normalize("COMPSCI 61A") == "COMPSCI 61A"
    assert PrioritySpec.normalize("compsci") == "COMPSCI"


def test_spaced_patterns_match_space_free_course_keys() -> None:
    spec = PrioritySpec.from_text("EL ENG *\nPOL SCI 1\nNUC ENG *\nCOMPSCI *\nMATH 1*\n")
    assert spec.patterns == ("ELENG *", "POLSCI 1", "NUCENG *", "COMPSCI *", "MATH 1*")
    assert spec.matches("ELENG 16A")
    assert spec.matches("EL ENG 16A")  # sis_api / berkeleytime raw spelling, should it ever leak through
    assert spec.matches("POLSCI 1") and not spec.matches("POLSCI 2")
    assert spec.matches("NUCENG 10")
    assert spec.matches("COMPSCI 61A")
    assert spec.matches("MATH 1A") and spec.matches("MATH 16A") and not spec.matches("MATH 53")


def test_bare_subject_pattern_matches_every_catalog_number() -> None:
    spec = PrioritySpec.from_text("COMPSCI\nELENG\n")
    assert spec.matches("COMPSCI 61A") and spec.matches("ELENG 16A")
    assert not spec.matches("EECS 16A")


def test_sha_is_of_the_raw_text() -> None:
    a = PrioritySpec.from_text("EL ENG *\n")
    b = PrioritySpec.from_text("ELENG *\n")
    assert a.patterns == b.patterns and a.sha != b.sha


def test_shipped_priority_file_matches_live_site_spellings() -> None:
    """The list installed on 2026-09-24 (docs/DATA_LOG.md priority_list row): generated by
    analysis/priority_from_flows.py from both finished cycles (top 1,500 sections by joins, plus
    every course with at least 100 joins), in joins order, exact course keys as
    classes.berkeley.edu spells them. MATH 1A/1B are absent on purpose: Fall 2026 lists calculus
    as MATH 51 and 52."""
    spec = PrioritySpec.from_file(PRIORITY_FILE)
    assert len(spec.patterns) == 1013  # generated file: the sha in the data log is the real guard
    assert all(" " in pat and "*" not in pat for pat in spec.patterns)  # exact courses, no wildcards, no bare subjects
    for key in (
        "PHYSED 1", "MATH 54", "CHEM 1A", "COMPSCI 61B", "COMPSCI 189", "MATH 52", "MATH 51", "DATA C8",
        "UGBA 135", "COMPSCI 188", "MATH 53", "ESPM 50AC", "CHEM 3A", "COMPSCI 61A", "STAT 134",
        "ECON 1", "ECON 100A", "PSYCH 1", "PHYSICS 7A", "EECS 16A", "POLSCI 1", "SOCIOL 1", "PHILOS 2",
        "MECENG 40", "MEC ENG 40", "INTEGBI 131", "MCELLBI 32",
        "COLWRIT R1A", "COLWRIT R4A", "COLWRIT R4B", "ENGLISH R1A", "ENGLISH R1B",  # by course total
    ):
        assert spec.matches(key), key
    for key in ("MATH 1A", "MATH 1B", "AEROENG 10", "PSYCH 2", "AFRICAM R1B"):
        assert not spec.matches(key), key
    # Order matters: courses by reconstructed joins, most-joined first.
    assert spec.rank("PHYSED 1") < spec.rank("MATH 54") < spec.rank("CHEM 1A") < spec.rank("COMPSCI 61B") < spec.rank("COMPSCI 61A")
