"""Write config/subject_names.json from the public Berkeley Academic Guide subject list.

The Guide's "Courses" index lists every subject as ``Name (CODE)``; this reads it
once with stdlib ``urllib``, squashes the code the way the catalog does
(``AERO ENG`` -> ``AEROENG``, ``L&S`` -> ``LS``), keeps only the subjects that
appear in ``site/data/index.json`` and writes the map with its source URL and
fetch date.  Nothing is fetched from classes.berkeley.edu: ``/search/`` is
disallowed by its robots.txt and the scraper's request budget is not this
script's to spend.

``guide.berkeley.edu/courses/`` now redirects to the registrar's catalog page,
which is a JavaScript application with no subject list in its HTML, so the
script falls back to the last Academic Guide snapshot in the public Internet
Archive and records *that* URL as the source.

The same run rewrites the generated block in ``site/assets/site.js`` (the site
is static and ships only ``site/``, so the names have to travel in the script)
and embeds ``config/course_nicknames.json``, which it only ever reads.

    python scripts/subject_names.py [--check]

``--check`` fetches nothing: it only verifies that the committed JSON and the
block in site.js agree, which is what tests/test_site.py asserts.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import ssl
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAMES_FILE = ROOT / "config" / "subject_names.json"
NICKNAMES_FILE = ROOT / "config" / "course_nicknames.json"
INDEX_FILE = ROOT / "site" / "data" / "index.json"
SITE_JS = ROOT / "site" / "assets" / "site.js"

GUIDE_URL = "https://guide.berkeley.edu/courses/"
# The Guide's own index moved behind a JavaScript catalogue in 2025; this is the
# last snapshot of it that still serves the "Name (CODE)" list as HTML.
ARCHIVE_URL = "https://web.archive.org/web/20250527071117id_/https://guide.berkeley.edu/courses/"
USER_AGENT = "berkeley-waitlist-odds/1.0 (+https://github.com/oliver139-chinesemole/berkeley-waitlist-odds)"

# Subjects that appear in the catalog but not in the Guide's index; names are text,
# not measurements, so the residue is typed by hand. Leave a code out of here and
# it is written with an empty name and listed under "_todo".
MANUAL: dict[str, str] = {}

BEGIN = "  // >>> generated by scripts/subject_names.py; run it, do not edit by hand"
END = "  // <<< generated"
SUBJECT_LINK = re.compile(r'<a href="/courses/[a-z0-9_.-]+/">([^<]+?)\s*\(([^()<]+)\)</a>')


def squash(code: str) -> str:
    """The space-free spelling the catalog uses (docs/DESIGN_A2.md section 1)."""
    return re.sub(r"[^A-Z0-9]", "", code.upper())


def fetch(url: str) -> str:
    context = ssl.create_default_context()
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=60, context=context) as response:
            return response.read().decode("utf-8", "replace")
    except urllib.error.URLError as err:  # a python.org build with no system CA bundle
        if "CERTIFICATE_VERIFY_FAILED" not in str(err):
            raise
        import certifi  # installed with requests; only reached on such a build

        context = ssl.create_default_context(cafile=certifi.where())
        with urllib.request.urlopen(request, timeout=60, context=context) as response:
            return response.read().decode("utf-8", "replace")


def parse(page: str) -> dict[str, str]:
    """``{"COMPSCI": "Computer Science", ...}`` from the Guide's index."""
    found: dict[str, str] = {}
    for match in SUBJECT_LINK.finditer(page):
        name, code = html.unescape(match.group(1)).strip(), squash(match.group(2))
        if code and name:
            found.setdefault(code, name)
    return found


def subjects_in_catalog() -> list[str]:
    index = json.loads(INDEX_FILE.read_text())
    return sorted({row["subject"] for row in index["courses"]})


def nicknames() -> dict[str, str]:
    return json.loads(NICKNAMES_FILE.read_text())["nicknames"]


def js_block(names: dict[str, str], nicks: dict[str, str]) -> str:
    """The lines site.js carries between the generated markers."""
    def literal(mapping: dict[str, str]) -> str:
        """``{ "CODE": "Name", ... }``, wrapped so no line runs past about 150 characters."""
        if not mapping:
            return "{}"
        lines, row = [], "  "
        for code, name in mapping.items():
            pair = f"{json.dumps(code)}: {json.dumps(name)},"
            if len(row) + 1 + len(pair) > 150:
                lines.append(row)
                row = "  "
            row += (" " if row.strip() else "") + pair
        lines.append(row)
        return "{\n" + "\n".join(lines) + "\n  }"

    named = {code: name for code, name in names.items() if name}
    lines = [
        BEGIN,
        "  // Display names for every subject in site/data/index.json, from config/subject_names.json.",
        f"  const SUBJECT_NAMES = {literal(named)};",
        "  // Hand-written nicknames, from config/course_nicknames.json.",
        f"  const COURSE_NICKNAMES = {literal(nicks)};",
        END,
    ]
    return "\n".join(lines)


def write_js(names: dict[str, str], nicks: dict[str, str]) -> None:
    source = SITE_JS.read_text()
    start, end = source.find(BEGIN), source.find(END)
    if start < 0 or end < 0:
        raise SystemExit(f"generated markers not found in {SITE_JS}")
    SITE_JS.write_text(source[:start] + js_block(names, nicks) + source[end + len(END):])


def check() -> int:
    stored = json.loads(NAMES_FILE.read_text())
    block = js_block(stored["names"], nicknames())
    if block not in SITE_JS.read_text():
        print(f"{SITE_JS} is out of date; run python scripts/subject_names.py", file=sys.stderr)
        return 1
    print(f"{NAMES_FILE.name} and {SITE_JS.name} agree ({len(stored['names'])} subjects)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the committed files agree; fetch nothing")
    args = parser.parse_args()
    if args.check:
        return check()

    url = GUIDE_URL
    found = parse(fetch(url))
    if not found:
        url = ARCHIVE_URL
        found = parse(fetch(url))
    if not found:
        raise SystemExit("no subjects parsed; the Guide's index has moved again")

    names = {code: found.get(code, MANUAL.get(code, "")) for code in subjects_in_catalog()}
    todo = sorted(code for code, name in names.items() if not name)
    payload = {
        "_source": url,
        "_fetched": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "_note": (
            "Generated by scripts/subject_names.py from the Berkeley Academic Guide's subject index "
            "('Name (CODE)'); one code per subject in site/data/index.json. Codes under '_todo' are not "
            "in the Guide's index and have no name yet. Hand-written nicknames live in course_nicknames.json."
        ),
        "_todo": todo,
        "names": names,
    }
    NAMES_FILE.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    write_js(names, nicknames())
    print(f"{len(names) - len(todo)} of {len(names)} subjects named from {url}; {len(todo)} to do: {', '.join(todo) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
