"""Write config/subject_names.json from the public Berkeley Academic Guide subject list.

The Guide's "Courses" index lists every subject as ``Name (CODE)``; this reads it
once with stdlib ``urllib``, squashes the code the way the catalog does
(``AERO ENG`` -> ``AEROENG``, ``L&S`` -> ``LS``), keeps only the subjects that
appear in the course index it is run over (``site/data/index.json`` unless
``--index`` names another) and writes the map with its source URL and fetch
date.  A code already in ``config/subject_names.json`` is kept, so the file
covers every term's index the script has been run over: the site switches terms
by swapping ``site/data`` (Fall 2026, then Spring 2026), and a name must not
vanish between the two.  Nothing is fetched from classes.berkeley.edu: ``/search/`` is
disallowed by its robots.txt and the scraper's request budget is not this
script's to spend.

``guide.berkeley.edu/courses/`` now redirects to the registrar's catalog page,
which is a JavaScript application with no subject list in its HTML, so the
script falls back to the last Academic Guide snapshot in the public Internet
Archive and records *that* URL as the source.

The Guide writes some names back to front, "Business Administration,
Undergraduate" and "Art, History of"; a name with exactly one comma is stored in
reading order ("Undergraduate Business Administration", "History of Art") and
its Guide spelling is kept under "aliases", so both reach the name route.  A
name with two or more commas is a list ("Theater, Dance, and Performance
Studies") and is left alone.

The same run rewrites the generated block in ``site/assets/site.js`` (the site
is static and ships only ``site/``, so the names have to travel in the script)
and embeds ``config/course_nicknames.json``, which it only ever reads.

    python scripts/subject_names.py [--index PATH] [--check]

``--check`` fetches nothing: it only verifies that the committed JSON and the
block in site.js agree and that every name is in reading order, which is what
tests/test_site.py asserts.
"""
from __future__ import annotations

import argparse
import html
import json
import re
import ssl
import sys
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
NAMES_FILE = ROOT / "config" / "subject_names.json"
NICKNAMES_FILE = ROOT / "config" / "course_nicknames.json"
INDEX_FILE = ROOT / "site" / "data" / "index.json"
SITE_JS = ROOT / "site" / "assets" / "site.js"

GUIDE_URL = "https://guide.berkeley.edu/courses/"
# The Guide's own index moved behind a JavaScript catalogue in 2025; this is the
# last snapshot of it that still serves the "Name (CODE)" list as HTML.
ARCHIVE_URL = "https://web.archive.org/web/20250527071117id_/https://guide.berkeley.edu/courses/"
USER_AGENT = "berkeley-waitlist-odds/1.0 (+https://github.com/oliver139-chinesemole/berkeley-waitlist-odds)"

# Subjects that appear in the catalog but not in the Guide's index; names are text,
# not measurements, so the residue is typed by hand. Leave a code out of here and
# it is written with an empty name and listed under "_todo".
MANUAL: dict[str, str] = {}

BEGIN = "  // >>> generated by scripts/subject_names.py; run it, do not edit by hand"
END = "  // <<< generated"
# A code with a space is written with a comma in the Guide's URLs (/courses/a,resec/).
SUBJECT_LINK = re.compile(r'<a href="/courses/[a-z0-9_.,-]+/">([^<]+?)\s*\(([^()<]+)\)</a>')


def squash(code: str) -> str:
    """The space-free spelling the catalog uses (docs/DESIGN_A2.md section 1)."""
    return re.sub(r"[^A-Z0-9]", "", code.upper())


def fetch(url: str) -> str:
    context = ssl.create_default_context()
    request = urllib.request.Request(url, headers={"User-Agent": USER_AGENT})
    try:
        with urllib.request.urlopen(request, timeout=60, context=context) as response:
            return response.read().decode("utf-8", "replace")
    except urllib.error.URLError as err:  # a python.org build with no system CA bundle
        if "CERTIFICATE_VERIFY_FAILED" not in str(err):
            raise
        import certifi  # installed with requests; only reached on such a build

        context = ssl.create_default_context(cafile=certifi.where())
        with urllib.request.urlopen(request, timeout=60, context=context) as response:
            return response.read().decode("utf-8", "replace")


def parse(page: str) -> dict[str, str]:
    """``{"COMPSCI": "Computer Science", ...}`` from the Guide's index."""
    found: dict[str, str] = {}
    for match in SUBJECT_LINK.finditer(page):
        name, code = html.unescape(match.group(1)).strip(), squash(match.group(2))
        if code and name:
            found.setdefault(code, name)
    return found


def reading_order(name: str) -> str:
    """ "Art, History of" -> "History of Art"; a name without exactly one comma is returned as it is."""
    head, sep, tail = name.partition(",")
    tail = tail.strip()
    if not sep or "," in tail or not tail or tail.lower().startswith("and "):
        return name
    return f"{tail} {head.strip()}"


def subjects_in_catalog(index_file: Path = INDEX_FILE) -> list[str]:
    """The subjects of the index being run over, plus every code the committed file already names."""
    index = json.loads(index_file.read_text())
    known = json.loads(NAMES_FILE.read_text())["names"] if NAMES_FILE.exists() else {}
    return sorted({row["subject"] for row in index["courses"]} | set(known))


def nicknames() -> dict[str, str]:
    return json.loads(NICKNAMES_FILE.read_text())["nicknames"]


def js_block(names: dict[str, str], aliases: dict[str, str], nicks: dict[str, str]) -> str:
    """The lines site.js carries between the generated markers."""
    def literal(mapping: dict[str, str]) -> str:
        """``{ "CODE": "Name", ... }``, wrapped so no line runs past about 150 characters."""
        if not mapping:
            return "{}"
        lines, row = [], "  "
        for code, name in mapping.items():
            pair = f"{json.dumps(code)}: {json.dumps(name)},"
            if len(row) + 1 + len(pair) > 150:
                lines.append(row)
                row = "  "
            row += (" " if row.strip() else "") + pair
        lines.append(row)
        return "{\n" + "\n".join(lines) + "\n  }"

    named = {code: name for code, name in names.items() if name}
    lines = [
        BEGIN,
        "  // Display names for every subject in site/data/index.json, from config/subject_names.json.",
        f"  const SUBJECT_NAMES = {literal(named)};",
        "  // The Guide's own spelling of the names stored in reading order above (\"Art, History of\").",
        f"  const SUBJECT_NAME_ALIASES = {literal(aliases)};",
        "  // Hand-written nicknames, from config/course_nicknames.json.",
        f"  const COURSE_NICKNAMES = {literal(nicks)};",
        END,
    ]
    return "\n".join(lines)


def write_js(names: dict[str, str], aliases: dict[str, str], nicks: dict[str, str]) -> None:
    source = SITE_JS.read_text()
    start, end = source.find(BEGIN), source.find(END)
    if start < 0 or end < 0:
        raise SystemExit(f"generated markers not found in {SITE_JS}")
    SITE_JS.write_text(source[:start] + js_block(names, aliases, nicks) + source[end + len(END):])


def check() -> int:
    stored = json.loads(NAMES_FILE.read_text())
    aliases = stored.get("aliases", {})
    backwards = sorted(code for code, name in stored["names"].items() if reading_order(name) != name)
    if backwards:
        print(f"{NAMES_FILE} has names not in reading order: {', '.join(backwards)}; run python scripts/subject_names.py", file=sys.stderr)
        return 1
    if any(reading_order(guide) != stored["names"].get(code) for code, guide in aliases.items()):
        print(f"{NAMES_FILE} has an alias that does not read back to its name; run python scripts/subject_names.py", file=sys.stderr)
        return 1
    block = js_block(stored["names"], aliases, nicknames())
    if block not in SITE_JS.read_text():
        print(f"{SITE_JS} is out of date; run python scripts/subject_names.py", file=sys.stderr)
        return 1
    print(f"{NAMES_FILE.name} and {SITE_JS.name} agree ({len(stored['names'])} subjects, {len(aliases)} in reading order)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--check", action="store_true", help="verify the committed files agree; fetch nothing")
    parser.add_argument("--index", type=Path, default=INDEX_FILE, help="the course index whose subjects to add (default: site/data/index.json)")
    args = parser.parse_args()
    if args.check:
        return check()

    url = GUIDE_URL
    found = parse(fetch(url))
    if not found:
        url = ARCHIVE_URL
        found = parse(fetch(url))
    if not found:
        raise SystemExit("no subjects parsed; the Guide's index has moved again")

    guide = {code: found.get(code, MANUAL.get(code, "")) for code in subjects_in_catalog(args.index)}
    names = {code: reading_order(name) for code, name in guide.items()}
    aliases = {code: name for code, name in guide.items() if names[code] != name}
    todo = sorted(code for code, name in names.items() if not name)
    payload = {
        "_source": url,
        "_fetched": datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        "_note": (
            "Generated by scripts/subject_names.py from the Berkeley Academic Guide's subject index "
            "('Name (CODE)'); one code per subject in every course index it has been run over (site/data/index.json "
            "for Fall 2026 and for Spring 2026), since a code once written is kept. A name the Guide writes 'X, Y' is stored as 'Y X' and its Guide spelling is kept under 'aliases'. "
            "Codes under '_todo' are not "
            "in the Guide's index and have no name yet. Hand-written nicknames live in course_nicknames.json."
        ),
        "_todo": todo,
        "names": names,
        "aliases": aliases,
    }
    NAMES_FILE.write_text(json.dumps(payload, indent=2, sort_keys=False) + "\n")
    write_js(names, aliases, nicknames())
    print(f"{len(names) - len(todo)} of {len(names)} subjects named from {url}; {len(todo)} to do: {', '.join(todo) or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
